### PR TITLE
Typos and Markdown syntax fixed

### PR DESCRIPTION
**Pull request by max123kl**
minor typos fixed
markdown syntax fixed as recommended by markdown linter

### CODE REVIEW

**Comment by max123kl** [comment]
This PR I have opened directly out of VSCodium.
If you are not sure how to handle it, pls ask

**Comment by ceford** [comment]
I am finding this PR confusing. When testing Joomla PRs I usually look at the list of **Files changed** but for this PR that is zero. If I look at the individual commits I see one with some of the changed lines reversed. For example, line 87 containing individuall and individually in pink or green. So I seem to need to remember which one to look at.

For now I have looked through the list of changes and used them to fix my source. I really need to learn exactly how to do merges because we may be doing a lot of them. But not today!

**Comment by max123kl** [comment]
Yes, this PR can be confusing. I had problems with my gpg verification and committed and reverted several times. Maybe that's why the commit is duplicated. 
You can also call up the diff view by clicking on the commit number (e78ff54 and f61296e). I can't explain why "Files changed" says zero. 
That's why it's best to close this PR and I'll create a new one.

For testing, we can use my J4.docs repo, of which you still have a fork.
I will prepare a small checklist that we can work through together.

Please inform me on Mattermost when you are ready (via email is too slow, I only retrieve the mails twice a day).

**Comment by ceford** [comment]
Archiving

**Pull request closed without merging**
