### PR TITLE
Enable Language support for German

### PR DESCRIPTION
**Pull request by max123kl**
de-DE *.ini files translated
The three .ini files for the German translation were created, and the corresponding folders were created for them.
For testing, the three files were manually added to the Joomla installation - now the component is available in German in the backend and frontend.
If further files need to be adapted, please let me know.

### CODE REVIEW

**Comment by ceford** [comment]
I have nearly finished a major revision of the Jdocmanual code. This has involved a lot of renaming, some additions and some deletions. I have included the three ini files in this PR directly in my source code so that I can do global key replacements. In a few days(?) I will upload the new code and close this PR. There will be more to check after that.

**Comment by max123kl** [comment]
As you added the files by hand, you can see conflicts next section.
Best is to close this PR now

**Comment by ceford** [comment]
Best not to do any more translations for now. I have not finished coding and I have noticed more problems with ini key values. And there may be a lot of unused keys, The PR diff shows the original content empty - which may mean you should have fetched the latest before translating. I usually get muddled on this fork, clone, fetch and push cycle so I don't know if I am at fault. I just feel I am trying to do too many different things!

**Comment by max123kl** [comment]
This PR does not include a translation.
It fixes some typos in the ReadMe

**Comment by ceford** [comment]
Sorry I never got around to dealing with pull requests. Closing as archiving.

**Pull request closed without merging**
